# Machine Learning Individual Assignment

<hr style="height:.9px;border:none;color:#333;background-color:#333;" /><br>
<strong>Paolo Musone </strong><br>

In [1]:
# importing libraries
import pandas as pd             # data science essentials
import numpy as np              # data science eesentials
import matplotlib.pyplot as plt # data visualization
import seaborn as sns           # enhanced data visualization
import statsmodels.formula.api as smf # linear regression (statsmodels)
from sklearn.model_selection import train_test_split # train/test split
from sklearn.metrics import confusion_matrix, classification_report # import confusion matrix and classfication
# new libraries
from sklearn.neighbors import KNeighborsRegressor # KNN for Regression
from sklearn.preprocessing import StandardScaler # standard scaler
from sklearn.linear_model import LinearRegression
import sklearn.linear_model 
from scipy.stats import skew


# reading the file into Python and naming the data set
df = pd.read_excel("C:/Users/paomu/Desktop/birthweight_low.xlsx")
    
# checking the file
df.head(n = 5) # check just in case

,mage,meduc,monpre,npvis,fage,feduc,omaps,fmaps,cigs,drink,male,mwhte,mblck,moth,fwhte,fblck,foth,bwght
0,23,11.0,4,11.0,46,12.0,8,9,13,4,0,0,0,1,0,1,0,3600
1,23,16.0,3,10.0,50,12.0,3,8,1,1,1,0,1,0,0,1,0,3912
2,24,16.0,1,12.0,26,16.0,6,9,21,4,0,0,0,1,0,0,1,3090
3,25,14.0,3,12.0,33,12.0,9,9,12,7,1,0,1,0,0,1,0,3370
4,25,12.0,2,8.0,32,12.0,9,9,4,3,0,0,1,0,0,1,0,3827

# Analyzing and Cleaning Data

<hr style="height:.9px;border:none;color:#333;background-color:#333;" /><br>
<strong>Descriptive statistics,Correlation,Replacing missing values </strong><br>

In [2]:
#showing the size of the data set
print(f"""
Observations: {df.shape[0]}
Features:     {df.shape[1]}
""")

#General desccriptive statistics of numerical variabels in the data set
df.describe(include = 'number').round(2)

Observations: 352
Features:     18

,mage,meduc,monpre,npvis,fage,feduc,omaps,fmaps,cigs,drink,male,mwhte,mblck,moth,fwhte,fblck,foth,bwght
count,352.00,349.00,352.00,349.00,352.00,345.00,352.00,352.00,352.00,352.00,352.00,352.00,352.00,352.00,352.00,352.00,352.00,352.00
mean,38.93,13.54,2.02,13.53,40.60,13.58,7.95,8.88,10.76,5.53,0.55,0.33,0.36,0.30,0.40,0.33,0.27,3246.09
std,10.36,2.29,0.34,6.32,12.21,2.97,2.02,0.79,6.95,3.87,0.50,0.47,0.48,0.46,0.49,0.47,0.45,757.70
min,21.00,0.00,1.00,2.00,19.00,0.00,1.00,5.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,697.00
25%,32.00,12.00,2.00,10.00,31.75,12.00,8.00,9.00,5.00,3.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,2867.75
50%,37.00,13.00,2.00,12.00,39.00,14.00,9.00,9.00,11.00,5.00,1.00,0.00,0.00,0.00,0.00,0.00,0.00,3349.00
75%,45.00,16.00,2.00,16.00,47.25,16.00,9.00,9.00,16.00,8.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,3778.75
max,73.00,18.00,7.00,42.00,72.00,19.00,10.00,10.00,32.00,21.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,4933.00

In [3]:
#Looking for missing values 
df.isnull().sum()

mage      0
meduc     3
monpre    0
npvis     3
fage      0
feduc     7
omaps     0
fmaps     0
cigs      0
drink     0
male      0
mwhte     0
mblck     0
moth      0
fwhte     0
fblck     0
foth      0
bwght     0
dtype: int64

In [4]:
#checking the variables skewness
print(df.skew(axis=0))

mage       0.921886
meduc     -0.993421
monpre    10.165080
npvis      1.334697
fage       0.796485
feduc     -1.466883
omaps     -2.062066
fmaps     -2.295921
cigs       0.075792
drink      0.583230
male      -0.183356
mwhte      0.714681
mblck      0.569376
moth       0.855975
fwhte      0.419718
fblck      0.728372
foth       1.024994
bwght     -0.767405
dtype: float64

In [5]:
# creating a (Pearson) correlation matrix to get some insights on what are the most valuable variables

df_corr = df.corr().round(2)
#fmaps  omaps  npvis 


# printing (Pearson) correlations with bwght
print(df_corr.loc['bwght'].sort_values(ascending = False))

bwght     1.00
fmaps     0.46
omaps     0.45
npvis     0.30
feduc     0.24
meduc     0.20
moth      0.10
foth      0.05
mblck     0.04
fblck     0.03
monpre    0.02
male      0.02
fwhte    -0.07
mwhte    -0.14
mage     -0.48
cigs     -0.57
fage     -0.58
drink    -0.67
Name: bwght, dtype: float64

In [6]:
#Replacing missing valeus with the column median 
df['meduc']             = df['meduc'].fillna(df['meduc'].median())
df['npvis']             = df['npvis'].fillna(df['npvis'].median())
df['feduc']             = df['feduc'].fillna(df['feduc'].median())

# Feature Engineering

<hr style="height:.9px;border:none;color:#333;background-color:#333;" /><br>
<strong>Creating a new variable based on the original data set </strong><br>

In [7]:
#Creating a new variable for 'drink_smoke'
df['drink_smoke'] = (df['drink']/7)*df['cigs']
# The idea of combining the two variables is to increase the weight of being a smoker and drinker on the regression model
df

,mage,meduc,monpre,npvis,fage,feduc,omaps,fmaps,cigs,drink,male,mwhte,mblck,moth,fwhte,fblck,foth,bwght,drink_smoke
0,23,11.0,4,11.0,46,12.0,8,9,13,4,0,0,0,1,0,1,0,3600,7.428571
1,23,16.0,3,10.0,50,12.0,3,8,1,1,1,0,1,0,0,1,0,3912,0.142857
2,24,16.0,1,12.0,26,16.0,6,9,21,4,0,0,0,1,0,0,1,3090,12.000000
3,25,14.0,3,12.0,33,12.0,9,9,12,7,1,0,1,0,0,1,0,3370,12.000000
4,25,12.0,2,8.0,32,12.0,9,9,4,3,0,0,1,0,0,1,0,3827,1.714286
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
347,61,11.0,2,11.0,69,10.0,4,6,25,11,1,1,0,0,1,0,0,1290,39.285714
348,40,12.0,2,7.0,49,12.0,1,8,17,13,0,1,0,0,1,0,0,1956,31.571429
349,45,12.0,2,6.0,71,11.0,2,6,21,12,1,0,1,0,0,1,0,1490,36.000000
350,46,12.0,2,13.0,55,13.0,8,8,17,12,1,0,1,0,0,1,0,2050,29.142857
351,62,13.0,2,10.0,68,11.0,4,5,25,11,1,1,0,0,1,0,0,1290,39.285714

In [8]:
# creating a (Pearson) correlation matrix
df_corr = df.corr().round(2)
#fmaps  omaps  npvis 


# printing (Pearson) correlations with bwght to check the new variabels correlation
print(df_corr.loc['bwght'].sort_values(ascending = False))

bwght          1.00
fmaps          0.46
omaps          0.45
npvis          0.30
feduc          0.23
meduc          0.20
moth           0.10
foth           0.05
mblck          0.04
fblck          0.03
monpre         0.02
male           0.02
fwhte         -0.07
mwhte         -0.14
mage          -0.48
cigs          -0.57
fage          -0.58
drink         -0.67
drink_smoke   -0.80
Name: bwght, dtype: float64

# OLS Regression Model

<hr style="height:.9px;border:none;color:#333;background-color:#333;" /><br>
<strong>Preparing the training and testing set.Running the OLS Regression Model and testing it  </strong><br>

In [9]:
# preparing explanatory variable data
df_data   = df.drop(['bwght'],axis = 1)


# preparing response variable data
df_target = df.loc[ : , 'bwght']



# preparing training and testing sets (all letters are lowercase)
x_train, x_test, y_train, y_test = train_test_split(
            df_data,
            df_target,
            test_size = 0.25,
            random_state = 219)


# checking the shapes of the datasets
print(f"""
Training Data
-------------
X-side: {x_train.shape}
y-side: {y_train.shape[0]}


Testing Data
------------
X-side: {x_test.shape}
y-side: {y_test.shape[0]}
""")

Training Data
-------------
X-side: (264, 18)
y-side: 264


Testing Data
------------
X-side: (88, 18)
y-side: 88

In [10]:
# declaring set of x-variables
x_variables = ['drink_smoke', 'npvis',
               'fage', 'mwhte', 'male','mage','monpre']

# looping to make x-variables suitable for statsmodels
for val in x_variables:
    print(f"{val} +")

drink_smoke +
npvis +
fage +
mwhte +
male +
mage +
monpre +

In [11]:
# merging X_train and y_train so that they can be used in statsmodels
df_train = pd.concat([x_train, y_train], axis = 1)


# Step 1: build a model
lm_best = smf.ols(formula =  """bwght ~ 
drink_smoke +
mage +
npvis +
fage +
mwhte +
male +
monpre """,
                                data = df_train)


# Step 2: fit the model based on the data
results = lm_best.fit()



# Step 3: analyze the summary output
print(results.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                  bwght   R-squared:                       0.661
Model:                            OLS   Adj. R-squared:                  0.652
Method:                 Least Squares   F-statistic:                     71.28
Date:                Tue, 15 Mar 2022   Prob (F-statistic):           1.58e-56
Time:                        18:57:45   Log-Likelihood:                -1982.1
No. Observations:                 264   AIC:                             3980.
Df Residuals:                     256   BIC:                             4009.
Df Model:                           7
Covariance Type:            nonrobust
===============================================================================
                  coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------
Intercept    3763.8584    283.178     13.292      0.000    3206.204    4321.513
drink_smoke   -43.3862      3.030    -14.318      0.000     -49.353     -37.419
mage           -5.3615      3.805     -1.409      0.160     -12.854       2.131
npvis          17.0680      4.619      3.695      0.000       7.971      26.165
fage           -9.0144      3.414     -2.640      0.009     -15.738      -2.291
mwhte        -167.3825     60.176     -2.782      0.006    -285.885     -48.880
male          111.5465     56.482      1.975      0.049       0.318     222.775
monpre        131.4357    116.415      1.129      0.260     -97.817     360.688
==============================================================================
Omnibus:                       35.154   Durbin-Watson:                   1.884
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              103.043
Skew:                           0.553   Prob(JB):                     4.21e-23
Kurtosis:                       5.854   Cond. No.                         656.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [12]:


# Preparing a DataFrame based the the analysis above
ols_data   = df.loc[ : , x_variables]


# Preparing the target variable
df_target = df.loc[ : , 'bwght']


###############################################
## setting up more than one train-test split ##
###############################################
# FULL X-dataset (normal Y)
x_train_FULL, x_test_FULL, y_train_FULL, y_test_FULL = train_test_split(
            df_data,     # x-variables
            df_target,   # y-variable
            test_size = 0.25,
            random_state = 219)


# OLS p-value x-dataset (normal Y)
x_train_OLS, x_test_OLS, y_train_OLS, y_test_OLS = train_test_split(
            ols_data,         # x-variables
            df_target,   # y-variable
            test_size = 0.25,
            random_state = 219)

In [13]:
# INSTANTIATING a model object
lr = LinearRegression()


# FITTING to the training data
lr_fit = lr.fit(x_train_OLS, y_train_OLS)


# PREDICTING on new data
lr_pred = lr_fit.predict(x_test_OLS)


# SCORING the results
print('OLS Training Score :', lr.score(x_train_OLS, y_train_OLS).round(4))
print('OLS Testing Score  :', lr.score(x_test_OLS, y_test_OLS).round(4))


# saving scoring data for future use
lr_train_score = lr.score(x_train_OLS, y_train_OLS).round(4) # using R-square
lr_test_score  = lr.score(x_test_OLS, y_test_OLS).round(4)   # using R-square


# displaying and saving the gap between training and testing
print('OLS Train-Test Gap :', abs(lr_train_score - lr_test_score).round(4))
lr_test_gap = abs(lr_train_score - lr_test_score).round(4)

OLS Training Score : 0.6609
OLS Testing Score  : 0.7433
OLS Train-Test Gap : 0.0824

# Lasso Regression Model

<hr style="height:.9px;border:none;color:#333;background-color:#333;" /><br>
<strong>Running the Lasso Regression Model and testing it  </strong><br>

In [14]:
# INSTANTIATING a model object
lasso_model = sklearn.linear_model.Lasso(alpha     = 1.0,  # default shrinkage
                                         normalize = True) # default magitude


# FITTING to the training data
lasso_fit = lasso_model.fit(x_train_FULL, y_train_FULL)


# PREDICTING on new data
lasso_pred = lasso_fit.predict(x_test_FULL)


# SCORING the results
print('Lasso Training Score :', lasso_model.score(x_train_FULL, y_train_FULL).round(4))
print('Lasso Testing Score  :', lasso_model.score(x_test_FULL, y_test_FULL).round(4))


## the following code has been provided for you ##

# saving scoring data for future use
lasso_train_score = lasso_model.score(x_train_FULL, y_train_FULL).round(4) # using R-square
lasso_test_score  = lasso_model.score(x_test_FULL, y_test_FULL).round(4)   # using R-square


# displaying and saving the gap between training and testing
print('Lasso Train-Test Gap :', abs(lasso_train_score - lasso_test_score).round(4))
lasso_test_gap = abs(lasso_train_score - lasso_test_score).round(4)

Lasso Training Score : 0.663
Lasso Testing Score  : 0.7687
Lasso Train-Test Gap : 0.1057

C:\Users\paomu\anaconda3\lib\site-packages\sklearn\linear_model\_base.py:141: FutureWarning: 'normalize' was deprecated in version 1.0 and will be removed in 1.2.
If you wish to scale the data, use Pipeline with a StandardScaler in a preprocessing stage. To reproduce the previous behavior:

from sklearn.pipeline import make_pipeline

model = make_pipeline(StandardScaler(with_mean=False), Lasso())

If you wish to pass a sample_weight parameter, you need to pass it as a fit parameter to each step of the pipeline as follows:

kwargs = {s[0] + '__sample_weight': sample_weight for s in model.steps}
model.fit(X, y, **kwargs)

Set parameter alpha to: original_alpha * np.sqrt(n_samples).
  warnings.warn(

# ARD Model

<hr style="height:.9px;border:none;color:#333;background-color:#333;" /><br>
<strong>Running the ARD Model and testing it  </strong><br>

In [15]:
# INSTANTIATING a model object
ard_model = sklearn.linear_model.ARDRegression(normalize  = False)


# FITTING the training data
ard_fit = ard_model.fit(x_train_FULL, y_train_FULL)


# PREDICTING on new data
ard_pred = ard_fit.predict(x_test_FULL)


print('Training Score:', ard_model.score(x_train_FULL, y_train_FULL).round(4))
print('Testing Score :',  ard_model.score(x_test_FULL, y_test_FULL).round(4))


# saving scoring data for future use
ard_train_score = ard_model.score(x_train_FULL, y_train_FULL).round(4)
ard_test_score  = ard_model.score(x_test_FULL, y_test_FULL).round(4)


# displaying and saving the gap between training and testing
print('ARD Train-Test Gap :', abs(ard_train_score - ard_test_score).round(4))
ard_test_gap = abs(ard_train_score - ard_test_score).round(4)

Training Score: 0.6751
Testing Score : 0.7751
ARD Train-Test Gap : 0.1

C:\Users\paomu\anaconda3\lib\site-packages\sklearn\linear_model\_base.py:148: FutureWarning: 'normalize' was deprecated in version 1.0 and will be removed in 1.2. Please leave the normalize parameter to its default value to silence this warning. The default behavior of this estimator is to not do any normalization. If normalization is needed please use sklearn.preprocessing.StandardScaler instead.
  warnings.warn(

# Final Result

<hr style="height:.9px;border:none;color:#333;background-color:#333;" /><br>
<strong>Showing and comparing the Model scores   </strong><br>

In [16]:
#showing the result with dynamic string

print(f"""
Model      Train Score      Test Score      Train-Test Gap
-----      -----------      ----------      ----------
OLS *         {lr_train_score}           {lr_test_score}             {lr_test_gap}
Lasso        {lasso_train_score}           {lasso_test_score}           {lasso_test_gap}
ARD         {ard_train_score}           {ard_test_score}              {ard_test_gap}

*Final model""")



# creating a dictionary for model results
model_performance = {
    
    'Model Type'    : ['OLS', 'Lasso', 'ARD'],
           
    'Training' : [lr_train_score, lasso_train_score,
                                   ard_train_score],
           
    'Testing'  : [lr_test_score, lasso_test_score,
                                   ard_test_score],
                    
    'Train-Test Gap' : [lr_test_gap, lasso_test_gap,
                                        ard_test_gap]}

Model      Train Score      Test Score      Train-Test Gap
-----      -----------      ----------      ----------
OLS *         0.6609           0.7433             0.0824
Lasso        0.663           0.7687           0.1057
ARD         0.6751           0.7751              0.1

*Final model